version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: marketplace-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: marketplace
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/src/utils/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - marketplace-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password123@mongodb:27017/marketplace?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-for-production
      JWT_ACCESS_EXPIRES: 15m
      JWT_REFRESH_EXPIRES: 30d
      FRONTEND_URL: http://localhost:3000
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    depends_on:
      - mongodb
    networks:
      - marketplace-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketplace-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - marketplace-network

volumes:
  mongodb_data:
    driver: local

networks:
  marketplace-network:
    driver: bridge
